# File sourced from https://github.com/ystorian/template

name: Deploy to Exoscale

on:
  push:
    branches: [ 'main' ]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Exoscale
        run: |
          repo_owner="ystorian"
          repo_name="ynfra"
          event_type={event_type}

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.YNFRA_WORKFLOW_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {}}"
