# File sourced from https://github.com/ystorian/template

name: main

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 0 1 * *

env:
  CARGO_INCREMENTAL: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

	  - name: cargo build
		id: build
		run: cargo build {workspace} {features}

	  - name: Install nextest
		if: steps.build.outcome == 'success'
		uses: taiki-e/install-action@nextest

	  - name: cargo nextest
		if: steps.build.outcome == 'success'
		run: cargo nextest run {workspace} {features}

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

	  - name: cargo build
		if: steps.build.outcome == 'success'
		run: cargo build {workspace} {features}

	  - name: Install nextest
		if: steps.build.outcome == 'success'
		uses: taiki-e/install-action@nextest

	  - name: cargo nextest
		if: steps.build.outcome == 'success'
		run: cargo nextest run {workspace} {features}

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

	  - name: cargo build
		id: build
		run: cargo build {workspace} {features}

	  - name: Install nextest
		if: steps.build.outcome == 'success'
		uses: taiki-e/install-action@nextest

	  - name: cargo nextest
		if: steps.build.outcome == 'success'
	    run: cargo nextest run {workspace} {features}
