# File sourced from https://github.com/ystorian/template

name: PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_INCREMENTAL: 1

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: cargo build
        id: build
        run: {build_command}

      - name: Install nextest
        if: steps.build.outcome == 'success'
        uses: taiki-e/install-action@nextest

      - name: cargo nextest
        run: {test_command}

      - name: cargo fmt
        run: {fmt_command}

      - name: cargo clippy
        run: {clippy_command}

  test-windows:
    needs: [test-linux]
    if: needs.test-linux.result == 'success'
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: cargo build
        id: build
        run: {build_command}

      - name: Install nextest
        if: steps.build.outcome == 'success'
        uses: taiki-e/install-action@nextest

      - name: cargo nextest
        run: {test_command}

  test-macos:
    needs: [test-linux]
    if: needs.test-linux.result == 'success'
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: cargo build
        id: build
        run: {build_command}

      - name: Install nextest
        if: steps.build.outcome == 'success'
        uses: taiki-e/install-action@nextest

      - name: cargo nextest
        if: steps.build.outcome == 'success'
        run: {test_command}
