# File sourced from https://github.com/ystorian/template

name: Pre-release

on:
  push:
    branches: [ pre-release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          - stable
          - {package_msrv} # MSRV (Minimal Supported Rust Version)

    name: ${{ matrix.os }} - ${{ matrix.rust == 'stable' && 'stable' || 'msrv' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: rustup update
        run: {rustup_command}

      - name: Setup Rust toolchain (${{ matrix.rust }})
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: cargo build
        run: {build_command}

      {check_command}

      - name: cargo test
        run: {test_command}

      - name: cargo fmt
        run: {fmt_command}

      - name: cargo clippy (pedantic)
        run: {clippy_pedantic}

      - name: cargo-deny
        if: matrix.os == 'ubuntu-latest'
        uses: EmbarkStudios/cargo-deny-action@v1

      - name: cargo-audit
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cargo-msrv
        if: matrix.rust == 'stable'
        run: cargo install cargo-msrv

      - name: cargo-msrv
        if: matrix.rust == 'stable'
        run: cargo msrv --verify
{semver_checks}
