#! /usr/bin/bash

clippy_args="-- -W clippy::all -W clippy::pedantic -W clippy::restriction -W clippy::nursery \
    -D warnings"

if grep -wq "\[features\]" Cargo.toml && grep -wq "\[workspace\]" Cargo.toml
then
    cargo_check="cargo check --all-features --workspace"
    cargo_test="cargo test --all-features --workspace"
    cargo_clippy="cargo clippy --all-features --workspace"
elif grep -wq "\[features\]" Cargo.toml
then
    cargo_check="cargo check --all-features"
    cargo_test="cargo test --all-features"
    cargo_clippy="cargo clippy --all-features"
elif grep -wq "\[workspace\]" Cargo.toml
then
    cargo_check="cargo check --workspace"
    cargo_test="cargo test --workspace"
    cargo_clippy="cargo clippy --workspace"
else
    cargo_check="cargo check"
    cargo_test="cargo test"
    cargo_clippy="cargo clippy"
fi

cargo_fmt="cargo fmt --all --check"

echo execution

if ! $cargo_check || ! $cargo_test || ! $cargo_clippy || ! $cargo_fmt
then
    echo test unsuccessful
    exit 1
else
    echo test successful
    exit 0
fi
