# File sourced from https://github.com/ystorian/template

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Build release (Linux)
        run: CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse cargo build --release --target=x86_64-unknown-linux-gnu

      - run: strip target/x86_64-unknown-linux-gnu/release/{package_name}

      - uses: actions/upload-artifact@v3
        with:
          name: build-linux
          path: target/x86_64-unknown-linux-gnu/release/{package_name}
  release:
    needs: [ build-linux ]
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - uses: actions/download-artifact@v3
        with:
          name: build-linux
          path: build-linux
      - run: mv build-linux/{package_name} build-linux/{package_name}-${{ steps.get_version.outputs.VERSION }}-linux-x86_64

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build-linux/*
