# File sourced from https://github.com/ystorian/template

name: Rust

on:
{trigger}

env:
  CARGO_TERM_COLOR: always

jobs:
{workflow_name}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Setup Rust toolchain (stable)
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy

{check_command}

      - name: Build
        run: {build_command}

      - name: Tests
        run: {test_command}

      - name: Format
        run: {fmt_command}

      - name: Lints
        run: {clippy_command}

      - name: cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1
