# File sourced from https://github.com/ystorian/template

name: rust

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 0 1 * *
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: rustup update
        run: {rustup_command}

      - name: Build
        run: {build_command}

      - name: Check
        run: {check_command}

      - name: Tests
        run: {test_command}

      - name: Format
        run: {fmt_command}

      - name: Lints
        run: {clippy_command}

  checks:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: rustup update
        run: {rustup_command}

      - name: Build
        run: {build_command}

      - name: Check
        run: {check_command}

      - name: Tests
        run: {test_command}
{doctests}
