# File sourced from https://github.com/ystorian/template

name: rust

on:
  push:
    branches-ignore: [ pre-release ]
  schedule:
    - cron: 0 0 1 * *

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-stable:
    name: ubuntu-latest - stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Setup Rust toolchain (stable)
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy

      - name: Build
        run: {build_command}

      - name: Check
        run: {check_command}

      - name: Tests
        run: {test_command}

      - name: Format
        run: {fmt_command}

      - name: Lints
        run: {clippy_command}
{doctests}

  checks:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        rust:
          - stable
          - 1.74.1 # MSRV (Minimal Supported Rust Version)
        exclude:
          - os: ubuntu-latest
            rust: stable

    name: ${{ matrix.os }} - ${{ matrix.rust == 'stable' && 'stable' || 'msrv' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Setup Rust toolchain (${{ matrix.rust }})
        run: crusty-pie/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
          components: rustfmt, clippy

      - name: Build
        run: {build_command}

      - name: Check
        run: {check_command}

      - name: Tests
        run: {test_command}

      - format: Format
        if: ${{ matrix.rust }} == stable
        run: {fmt_command}

      - name: Lints
        if: ${{ matrix.rust }} == stable
        run: {clippy_command}
{doctests}
