# File sourced from https://github.com/ystorian/template

name: rust

on:
  push:
    branches: [ main ]
    branches-ignore: [ pre-release ]
  schedule:
    - cron: 0 0 1 * *
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-stable:
    name: ubuntu-latest - stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: rustup update
        run: {rustup_command}

      - name: Setup Rust toolchain (stable)
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build
        run: {build_command}

      - name: Check
        run: {check_command}

      - name: Tests
        run: {test_command}

      - name: Format
        run: {fmt_command}

      - name: Lints
        run: {clippy_command}

  main-checks:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          - stable
          - 1.70.0 # MSRV (Minimal Supported Rust Version)
        exclude:
          - os: ubuntu-latest
            rust: stable

    name: ${{ matrix.os }} - ${{ matrix.rust == 'stable' && 'stable' || 'msrv' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: rustup update
        run: {rustup_command}

      - name: Setup Rust toolchain (${{ matrix.rust }})
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build
        run: {build_command}

      - name: Check
        run: {check_command}

      - name: Tests
        run: {test_command}
{doctests}
