# File sourced from https://github.com/ystorian/template

name: rust

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 0 1 * *
  pull_request:
    branches: [ main ]

env:
  CARGO_INCREMENTAL: 1

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            lint: 1

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: rustup update
        run: rustup update

      - name: build
        run: {build_command}

      - name: tests
        run: {test_command}
{doctests}
      - name: format
        if: github.event_name == 'pull_request' && matrix.lint
        run: {fmt_command}

      - name: lints
        if: github.event_name == 'pull_request' && matrix.lint
        run: {clippy_command}
