# File sourced from https://github.com/ystorian/template

name: Global sanity

on:
  schedule:
    - cron: 0 10 * * 2 # Runs at 10am UTC every Tuesday
  workflow_dispatch: # Allows manual triggering

jobs:
  sanity:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: rustup update
        run: rustup update

      {check_command}

      - name: cargo build
        run: {build_command}

      - name: cargo test
        run: {test_command}

      - name: cargo fmt
        run: {fmt_command}

      - name: cargo clippy
        run: {clippy_command}

      - name: cargo-deny
        if: matrix.os == 'ubuntu-latest'
        uses: EmbarkStudios/cargo-deny-action@v1

      - name: cargo-audit
        uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
