# File sourced from https://github.com/ystorian/template

name: Global sanity

on:
  schedule:
    - cron: 0 10 * * 2 # Runs at 10am UTC every Tuesday
  workflow_dispatch: # Allows manual triggering

jobs:
  sanity:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: rustup update
        run: rustup update

      - name: cargo check
        run: cargo check --all-features --workspace

      - name: cargo build
        run: cargo build --all-features --workspace

      - name: cargo test
        run: cargo test --all-features --workspace

      - name: cargo fmt
        run: cargo fmt --all --check

      - name: cargo clippy
        run: cargo clippy --tests --all-features --workspace -- -D warnings

      - name: cargo-deny
        if: matrix.os == 'ubuntu-latest'
        uses: EmbarkStudios/cargo-deny-action@v1

      - name: cargo-audit
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
