# File sourced from https://github.com/ystorian/template

name: Update deps

on:
  schedule:
    - cron: 0 10 * * 2
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - uses: mozilla-actions/sccache-action@v0.0.3

      - name: rustup update
        run: rustup update

      - name: cargo update
        run: cargo update

      - name: Open pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: cargo-update
          title: "cargo update"
          commit-message: "cargo: update"
          body: "Update dependencies to latest."
          reviewers: [ "cyann", "yozhgoor" ]
